{{- if or .Values.secrets.masterKey .Values.secrets.email.password .Values.secrets.additional }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferadb-control.secretName" . }}
  labels:
    {{- include "inferadb-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.masterKey }}
  masterKey: {{ .Values.secrets.masterKey | quote }}
  {{- end }}
  {{- if .Values.secrets.email.password }}
  emailPassword: {{ .Values.secrets.email.password | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additional }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
