{{- if or .Values.secrets.pem .Values.secrets.emailPassword .Values.secrets.additional }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inferadb-control.secretName" . }}
  labels:
    {{- include "inferadb-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.pem }}
  pem: {{ .Values.secrets.pem | quote }}
  {{- end }}
  {{- if .Values.secrets.emailPassword }}
  emailPassword: {{ .Values.secrets.emailPassword | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.additional }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
